preprocess:
  input: data/raw/data.csv
  output: data/processed/data.csv


train:
  input: data/processed/data.csv
  model: models/model.pkl
  random_state: 42
  n_estimator: 100
  max_depth: 100


evaluate:
  data: data/processed.csv
  model: models/model.pkl
